In [10]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [11]:
# 创建一个二维numpy数组，对角线是1，其余都是0
eye = np.eye(4)
print(f'numpy array: \n{eye}')

numpy array: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# 将numpy数组转换为csr格式的scipy稀疏矩阵
# 只保存非零元素
from scipy.sparse import csr_matrix
aparse_matrix = csr_matrix(eye)
print(f"scipy sparse csr matrix: \n{aparse_matrix}")


scipy sparse csr matrix:   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
